# Generated by Django 5.0.2 on 2024-02-20 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='ordertid',
        ),
    ]
