# Generated by Django 5.0.2 on 2024-02-20 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_remove_cart_ordertid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='stamp',
        ),
    ]
