# Generated by Django 5.0.2 on 2024-02-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_cart_stamp_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
