# Generated by Django 5.0.2 on 2024-04-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_remove_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordername', models.CharField(blank=True, max_length=100, null=True, verbose_name='รายการส่งซ่อม')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายละเอียดแจ้งซ่อม')),
                ('sentrepairby', models.CharField(max_length=60, verbose_name='ผู้แจ้งซ่อม')),
                ('stamp', models.DateTimeField(auto_now_add=True, null=True, verbose_name='วันที่แจ้ง')),
            ],
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
