# Generated by Django 5.0.2 on 2024-04-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_work_request_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_request',
            old_name='detail',
            new_name='detial',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
