# Generated by Django 5.0.2 on 2024-04-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_rename_detail_work_request_detial_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_request',
            old_name='ordername',
            new_name='title',
        ),
        migrations.AddField(
            model_name='work_request',
            name='Work_order',
            field=models.BigIntegerField(blank=True, max_length=100, null=True, verbose_name='เลขwork'),
        ),
        migrations.AddField(
            model_name='work_request',
            name='bound',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='bound'),
        ),
        migrations.AddField(
            model_name='work_request',
            name='equipment',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='doors'),
        ),
        migrations.AddField(
            model_name='work_request',
            name='serial',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='serial of product'),
        ),
        migrations.AddField(
            model_name='work_request',
            name='station',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='station'),
        ),
    ]
