# Generated by Django 5.0.2 on 2024-04-03 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_rename_ordername_work_request_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work_request',
            old_name='Work_order',
            new_name='work_order',
        ),
    ]
