# Generated by Django 5.0.2 on 2024-04-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_work_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_request',
            name='orderid',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
