# Generated by Django 5.0.2 on 2024-04-04 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_work_request_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_request',
            name='work_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='เลขwork'),
        ),
    ]
